### ISSUE TITLE
Internal Exception while using waterfall with 1.19.2

### ISSUE THREAD

**Issue by TechCallCP** [PurpurMC/PurpurDocs#53]
While using 1.19.2, I get an internal error while using waterfall proxy. I have never gotten or heard of this error before, but I have looked at every config, downgraded the server back to 1.19, and reinstalled both waterfall and purpur multiple times. The error is this:

Internal Exception: java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.world.entity.player.EntityHuman.fz()'

I run a community server and need to update it to support some of my plugins.
![console error](https://user-images.githubusercontent.com/88646131/189533405-72fdbadf-6fbd-4ed1-8be0-a037ca8f8eb4.png)

**Comment by theomega24** [comment]
Please join our discord and ask in #help-and-support

**Comment by TechCallCP** [comment]
> Please join our discord and ask in #help-and-support

I did, but your not an admin of the project are you?

**Comment by theomega24** [comment]
I am
