### ISSUE TITLE
 explosion-effect config description inconsistency

### ISSUE THREAD

**Issue by Blackrobe** [PurpurMC/PurpurDocs#72]
Hi, I want to report inconsistency in the documentation vs actual server value
https://purpurmc.org/docs/Configuration/explosion-effect_2

Key: `end-crystal.*.explosion-effect` (and possibly others like respawn anchor or bed in the nether)

It is said in the documentation

>explosion-effect
>    default: DESTROY
>    description: The type of explosion effect. Available values are NONE, BREAK, and DESTROY.

But when I try to set it to "BREAK" it is not accepted by the server:

```
[09:05:13 ERROR]: Unknown value for blocks.end-crystal.baseless.explosion-effect! Using default of BLOCK
[09:05:13 ERROR]: Unknown value for blocks.end-crystal.base.explosion-effect! Using default of BLOCK
```

Also in the documentation, the "BLOCK" option is nowhere to be seen in any config.

**Comment by granny** [comment]
This is actually a bug in Purpur that was pointed out by Billy. I've gone ahead and created your discussion post into an issue here: https://github.com/PurpurMC/Purpur/issues/1340 Sorry for the confusion.

**Comment by Blackrobe** [comment]
no worries, thank you @granny
